apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage
  sources:
    - repoURL: https://backstage.github.io/charts
      chart: backstage
      targetRevision: 2.10.0
      helm:
        valueFiles:
          - $values/backstage-values.yaml
    - repoURL: https://github.com/lukasb27/backstage-app.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - Replace=true
